#!/bin/bash
echo "---------USER DATA---------"
echo ""
echo "First name: $1"
echo "Last name: $2"
echo "Hello there $1 $2!" 
echo ""
echo "---------METADATA---------"
echo ""
echo "Name of the executed script: $0"
echo "# of given arguments by user: $#"
echo "Script PID: $$"
echo "Script Status: $?"
echo "All provided arguments by user: [$@]"
